version: '3.9'
services:
  web:
    image: 'server:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # host:container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: 'postgres:16'
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
